// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import LoadRecaptchaV2Controller from "./load_recaptcha_v2_controller"
application.register("load-recaptcha-v2", LoadRecaptchaV2Controller)
