default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost

development:
  <<: *default
  database: myappda_development
  password:

test:
  <<: *default
  database: myappda_test

production:
  <<: *default
  database: myappda_production
  username: myappda
  password: <%= ENV['MYAPPDA_DATABASE_PASSWORD'] %>
