# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 386681e69c21199e3bc050d52e46642ae0a1d5a6f334cb532d341c7e58e76033920f7462f4ff7b31cdb1083f491f9af01a7d914458a6d9ef7f9d21f9be428b00

test:
  secret_key_base: c3bca465d259ad924de15b5d029992752c2d71762c6cbbccda6cf098d11dc6bf50e3afa2b1ef23428cd4f5daf1be937e1384916841a4b57eb8eaa84dc12a58e9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
