:concurrency: 5

:queues:
    - default
    - mailers
    - insales_job
    - order_job
    - restock_job
    - preorder_job
    - abandoned_job
:max_retries: 3

development:
  :concurrency: 5
staging:
  :concurrency: 10
production:
  :concurrency: 30