:concurrency: 5

:queues:
    - default
    - mailers
    - insales_job
    - order_job
    - restock_job
    - preorder_job
    - abandoned_job
    - insint_job
    - bulk_delete
    - print
:max_retries: 3
:scheduler:
  :dynamic: true

development:
  :concurrency: 5
staging:
  :concurrency: 10
production:
  :concurrency: 20